apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHk2OTMuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImFHRjBhR0ZuWVd4bGRtbDJaV3MyT1RNMU9sWnBkbVZyTmprek5VQT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson